version: 2
jobs:
  tests:
    docker:
      - image: elixir:1.7.3
    working_directory: ~/dvr
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run:
          name: Run Tests
          command: |
            mix test

  typespecs:
    docker:
      - image: elixir:1.7.3
    working_directory: ~/dvr
    steps:
      - checkout
      - restore_cache:
          keys:
            - dvr-{{ checksum "mix.lock" }}-dependencies
      - run:
          name: Install deps
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run:
          name: Check Typespecs
          command: |
            mix dialyzer --halt-exit-status --format term
      - save_cache:
          key: dvr-{{ checksum "mix.lock" }}-dependencies
          paths:
            - '_build'
            - 'deps'
workflows:
  version: 2
  build:
    jobs:
      - tests
      - typespecs
